apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  ports:
  - port: 5001
    targetPort: 5000
    nodePort: 30500
  selector:
    app: registry
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry-sfs
spec:
  selector:
    matchLabels:
      app: registry
  serviceName: "registry"
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: registry-port
          containerPort: 5000
        volumeMounts:
        - mountPath: "/home"
          name: images
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
      volumes:
      - name: images
        persistentVolumeClaim:
          claimName: pvc-registry-images 
    
